<template><h1 id="stl-pageitem-分页项"><a class="header-anchor" href="#stl-pageitem-分页项">#</a> <a href="stl:pageItem">stl:pageItem</a> 分页项</h1>
<div class="language-markup ext-html line-numbers-mode"><pre v-pre class="language-markup"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>pageItem</span>
    <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>分页类型<span class="token punctuation">"</span></span>
    <span class="token attr-name">text</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>显示的文字<span class="token punctuation">"</span></span>
    <span class="token attr-name">linkClass</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>链接CSS样式<span class="token punctuation">"</span></span>
    <span class="token attr-name">textClass</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>文字CSS样式<span class="token punctuation">"</span></span>
    <span class="token attr-name">listNum</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>页导航或页跳转显示链接数<span class="token punctuation">"</span></span>
    <span class="token attr-name">listEllipsis</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>超出链接数使用的省略字符<span class="token punctuation">"</span></span>
    <span class="token attr-name">hasLr</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>页码导航是否包含左右字符<span class="token punctuation">"</span></span>
    <span class="token attr-name">lStr</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>页面左字符<span class="token punctuation">"</span></span>
    <span class="token attr-name">rStr</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>页面右字符<span class="token punctuation">"</span></span>
    <span class="token attr-name">alwaysA</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>页码总是超链接<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>pageItem</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br></div></div><h3 id="说明"><a class="header-anchor" href="#说明">#</a> 说明</h3>
<p>通过 <code>stl:pageItem</code> 标签在模板中显示分页项（上一页、下一页、当前页、页跳转、页导航等）</p>
<p>stl:pageItem 标签内可以嵌入代码，如果需要根据是否当前页显示不同的样式，需要使用子标签 <code>&lt;stl:yes&gt;</code> 和 <code>&lt;stl:no&gt;</code>，非当前页时将显示 <code>&lt;stl:yes&gt;</code> 中的内容，当前页时将显示 <code>&lt;stl:no&gt;</code> 中的内容。</p>
<p><code>&lt;stl:yes&gt;</code> 和 <code>&lt;stl:no&gt;</code> 通常包含 <code>&lt;a&gt;</code> 链接，其中可以包含 <code>{Current.Url}</code> 以及 <code>{Current.Num}</code> 实体，分别代表分页链接地址及当前页页码。</p>
<p>当 type 属性为&quot;FirstPage&quot;、&quot; PreviousPage&quot;、&quot; NextPage&quot;、&quot; LastPage&quot; 或 &quot;PageNavigation&quot; 之一时：</p>
<p>如果标签内未包含内容，系统将显示默认链接。 如果标签内包含内容，系统将指定的内容，同时将解析内容中包含的 <code>{Current.Url}</code> 及<code> {Current.Num}</code> 实体。 如果 标签内包含 <code>&lt;stl:yes&gt;</code> 及 <code>&lt;stl:no&gt;</code>，系统将根据是否当前页为对应页显示不同的内容，同时将解析子标签中包含的 <code>{Current.Url}</code> 及 <code>{Current.Num}</code> 实体。 当 type 属性为 &quot;CurrentPageIndex&quot; 或 &quot;TotalPageNum&quot; 时，分页项将显示当前页对应的页码及总页数。 当 type 属性为 &quot;PageSelect&quot; 时，分页项将显示分页跳转下拉框。</p>
<p>列表相关介绍请参见列表标签及列表项</p>
<p><code>&lt;stl:pageItem&gt;</code> 标签对应的实体为<code>{stl:pageItem}</code>。</p>
<h3 id="父标签"><a class="header-anchor" href="#父标签">#</a> 父标签</h3>
<p><code>&lt;stl:pageItem&gt;</code> 标签需要在标签 <code>&lt;stl:pageItems&gt;</code> 内使用。</p>
<table>
<thead>
<tr>
<th style="text-align:left">父标签</th>
<th style="text-align:left">说明</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">stl:pageItems</td>
<td style="text-align:left">分页项容器</td>
</tr>
</tbody>
</table>
<h3 id="子标签"><a class="header-anchor" href="#子标签">#</a> 子标签</h3>
<table>
<thead>
<tr>
<th style="text-align:left">子标签</th>
<th style="text-align:left">说明</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">stl:yes</td>
<td style="text-align:left">能够转到对应页面时的显示模板（非当前页），可以省略</td>
</tr>
<tr>
<td style="text-align:left">stl:no</td>
<td style="text-align:left">不能转到对应页面时的显示模板（当前页），可以省略</td>
</tr>
</tbody>
</table>
<h3 id="属性"><a class="header-anchor" href="#属性">#</a> 属性</h3>
<div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>所有属于HTML 标签<code>&lt;a&gt;</code>的属性均适用于<code>&lt;stl:pageItem&gt;</code>标签。</p>
</div>
<table>
<thead>
<tr>
<th style="text-align:left">属性</th>
<th style="text-align:left">说明</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">type</td>
<td style="text-align:left">分页类型</td>
</tr>
<tr>
<td style="text-align:left">text</td>
<td style="text-align:left">显示的文字</td>
</tr>
<tr>
<td style="text-align:left">linkClass</td>
<td style="text-align:left">链接CSS样式</td>
</tr>
<tr>
<td style="text-align:left">textClass</td>
<td style="text-align:left">文字CSS样式</td>
</tr>
<tr>
<td style="text-align:left">listNum</td>
<td style="text-align:left">页导航或页跳转显示链接数</td>
</tr>
<tr>
<td style="text-align:left">listEllipsis</td>
<td style="text-align:left">超出链接数使用的省略字符</td>
</tr>
<tr>
<td style="text-align:left">hasLr</td>
<td style="text-align:left">页码导航是否包含左右字符</td>
</tr>
<tr>
<td style="text-align:left">lStr</td>
<td style="text-align:left">页面左字符</td>
</tr>
<tr>
<td style="text-align:left">rStr</td>
<td style="text-align:left">页面右字符</td>
</tr>
<tr>
<td style="text-align:left">alwaysA</td>
<td style="text-align:left">页码总是超链接</td>
</tr>
</tbody>
</table>
<p><strong>type - 分页类型</strong></p>
<p>显示分页标签的类型。此属性只可属于以下可能的取值的一种。</p>
<ul>
<li>&quot;CurrentPageIndex&quot; 当前页索引</li>
<li>&quot;FirstPage&quot; 首页</li>
<li>&quot;LastPage&quot; 末页</li>
<li>&quot;NextPage&quot; 下一页</li>
<li>&quot;PageNavigation&quot; 页导航</li>
<li>&quot;PageSelect&quot; 页跳转</li>
<li>&quot;PreviousPage&quot; 上一页</li>
<li>&quot;TotalNum&quot; 总内容数</li>
<li>&quot;TotalPageNum&quot; 总页数</li>
</ul>
<p><strong>text - 显示的文字</strong></p>
<p>根据 type 属性的不同而显示不同的文字。</p>
<p><strong>linkClass - 链接CSS样式</strong></p>
<p>链接 CSS 类。</p>
<p><strong>textClass - 文字CSS样式</strong></p>
<p>非链接 CSS 类。</p>
<p>#listNum - 页导航或页跳转显示链接数
页导航或页跳转显示链接数。</p>
<p><strong>listEllipsis - 超出链接数使用的省略字符</strong></p>
<p>页导航或页跳转链接太多时显示的省略号。</p>
<p><strong>hasLr - 页码导航是否包含左右字符</strong></p>
<p>页码导航是否包含左右字符。</p>
<p><strong>lStr - 页面左字符</strong></p>
<p>页面左字符。</p>
<p><strong>rStr - 页面右字符</strong></p>
<p>页面右字符。</p>
<p><strong>alwaysA - 页码总是超链接</strong></p>
<p>页码总是超链接，包括无连接时。</p>
<h3 id="示例"><a class="header-anchor" href="#示例">#</a> 示例</h3>
<p><strong>显示分页项组合</strong></p>
<p>下面的例子显示分页项组合。</p>
<div class="language-markup ext-html line-numbers-mode"><pre v-pre class="language-markup"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>pageItems</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>table</span> <span class="token attr-name">width</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>100%<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>tr</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>td</span> <span class="token attr-name">align</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>left<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>pageItem</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>FirstPage<span class="token punctuation">"</span></span> <span class="token attr-name">text</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>首页<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>pageItem</span><span class="token punctuation">></span></span> |
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>pageItem</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>PreviousPage<span class="token punctuation">"</span></span> <span class="token attr-name">text</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>上一页<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>pageItem</span><span class="token punctuation">></span></span> |
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>pageItem</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>NextPage<span class="token punctuation">"</span></span> <span class="token attr-name">text</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>下一页<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>pageItem</span><span class="token punctuation">></span></span> |
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>pageItem</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>LastPage<span class="token punctuation">"</span></span> <span class="token attr-name">text</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>末页<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>pageItem</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>td</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>td</span><span class="token punctuation">></span></span> <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>td</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>td</span> <span class="token attr-name">align</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>right<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>pageItem</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>CurrentPageIndex<span class="token punctuation">"</span></span> <span class="token attr-name">text</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>当前页：<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>pageItem</span><span class="token punctuation">></span></span>/<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>pageItem</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>TotalPageNum<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>pageItem</span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>pageItem</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>PageNavigation<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>pageItem</span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>pageItem</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>PageSelect<span class="token punctuation">"</span></span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>input-small<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>pageItem</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>td</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>tr</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>table</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>pageItems</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br></div></div><p><strong>显示分页导航</strong></p>
<p>分页项根据是否当前页显示不同的风格</p>
<div class="language-markup ext-html line-numbers-mode"><pre v-pre class="language-markup"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>pageItems</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>pagination<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>ul</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>li</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>{PageItem.PreviousPage}<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>Prev<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>li</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>pageItem</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>PageNavigation<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>yes</span><span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>li</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>{Current.Url}<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>{Current.Num}<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>li</span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>yes</span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>no</span><span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>li</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>active<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>span</span><span class="token punctuation">></span></span>{Current.Num}<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>span</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>li</span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>no</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>pageItem</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>li</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>{PageItem.NextPage}<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>Next<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>li</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>ul</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>pageItems</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br></div></div><p><strong>显示上一页、数字导航及下一页</strong></p>
<p>下面的例子显示包含 CSS 样式的组合分页标签，可以直接拷贝到模板中使用。</p>
<div class="language-markup ext-html line-numbers-mode"><pre v-pre class="language-markup"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>style</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>text/css<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token style"><span class="token language-css">
<span class="token selector">.page_wrap</span><span class="token punctuation">{</span><span class="token property">clear</span><span class="token punctuation">:</span>both<span class="token punctuation">;</span> <span class="token property">margin-bottom</span><span class="token punctuation">:</span>10px<span class="token punctuation">;</span> <span class="token property">overflow</span><span class="token punctuation">:</span>hidden<span class="token punctuation">;</span><span class="token property">zoom</span><span class="token punctuation">:</span>1<span class="token punctuation">;</span><span class="token punctuation">}</span>
<span class="token selector">.paginator</span> <span class="token punctuation">{</span><span class="token property">float</span><span class="token punctuation">:</span>right<span class="token punctuation">;</span> <span class="token property">height</span><span class="token punctuation">:</span>25px<span class="token punctuation">;</span> <span class="token property">overflow</span><span class="token punctuation">:</span>hidden<span class="token punctuation">;</span> <span class="token punctuation">}</span>
<span class="token selector">.paginator,
.paginator input,
.paginator button</span> <span class="token punctuation">{</span><span class="token property">font-family</span><span class="token punctuation">:</span>Tahoma<span class="token punctuation">,</span> <span class="token string">"宋体"</span><span class="token punctuation">;</span> <span class="token property">font-size</span><span class="token punctuation">:</span>12px<span class="token punctuation">;</span> <span class="token punctuation">}</span>
<span class="token selector">.paginator a,
.paginator span</span> <span class="token punctuation">{</span><span class="token property">float</span><span class="token punctuation">:</span>left<span class="token punctuation">;</span> <span class="token property">height</span><span class="token punctuation">:</span>23px<span class="token punctuation">;</span> <span class="token property">margin</span><span class="token punctuation">:</span>0 5px 0 0<span class="token punctuation">;</span> <span class="token property">text-align</span><span class="token punctuation">:</span>center<span class="token punctuation">;</span> <span class="token property">white-space</span><span class="token punctuation">:</span>nowrap<span class="token punctuation">;</span> <span class="token property">vertical-align</span><span class="token punctuation">:</span>middle<span class="token punctuation">;</span> <span class="token property">line-height</span><span class="token punctuation">:</span>23px<span class="token punctuation">;</span> <span class="token property">background</span><span class="token punctuation">:</span>#fff<span class="token punctuation">;</span> <span class="token punctuation">}</span>
<span class="token selector">.paginator a</span> <span class="token punctuation">{</span><span class="token property">color</span><span class="token punctuation">:</span>#085C9B<span class="token punctuation">;</span> <span class="token punctuation">}</span>
<span class="token selector">.paginator b</span><span class="token punctuation">{</span><span class="token property">font-family</span><span class="token punctuation">:</span><span class="token string">"宋体"</span><span class="token punctuation">;</span> <span class="token property">margin</span><span class="token punctuation">:</span>3px<span class="token punctuation">;</span><span class="token property">font-weight</span><span class="token punctuation">:</span>300<span class="token punctuation">;</span><span class="token punctuation">}</span>
<span class="token selector">.paginator a:link,
.paginator a:visited,
.paginator a:hover,
.paginator a:active</span> <span class="token punctuation">{</span><span class="token property">text-decoration</span><span class="token punctuation">:</span>none<span class="token punctuation">;</span> <span class="token punctuation">}</span>
<span class="token selector">.paginator .page-start,
.paginator a,
.paginator .page-end</span> <span class="token punctuation">{</span><span class="token property">padding</span><span class="token punctuation">:</span>0 8px<span class="token punctuation">;</span> <span class="token property">border</span><span class="token punctuation">:</span>1px solid #D3D3D3<span class="token punctuation">;</span> <span class="token property">background</span><span class="token punctuation">:</span>#ffffff<span class="token punctuation">;</span> <span class="token punctuation">}</span>
<span class="token selector">.paginator .page-start</span> <span class="token punctuation">{</span><span class="token property">border-color</span><span class="token punctuation">:</span>#d9d9d9<span class="token punctuation">;</span> <span class="token property">color</span><span class="token punctuation">:</span>#d9d9d9<span class="token punctuation">;</span> <span class="token punctuation">}</span>
<span class="token selector">.paginator .page-end</span> <span class="token punctuation">{</span> <span class="token property">border-color</span><span class="token punctuation">:</span>#d9d9d9<span class="token punctuation">;</span>  <span class="token property">color</span><span class="token punctuation">:</span>#d9d9d9<span class="token punctuation">;</span> <span class="token punctuation">}</span>
<span class="token selector">.paginator .page-this,
.paginator .page-break</span> <span class="token punctuation">{</span><span class="token property">padding</span><span class="token punctuation">:</span>0 3px<span class="token punctuation">;</span> <span class="token punctuation">}</span>
<span class="token selector">.paginator .page-break</span> <span class="token punctuation">{</span><span class="token property">border</span><span class="token punctuation">:</span>1px solid #fff<span class="token punctuation">;</span> <span class="token punctuation">}</span>
<span class="token selector">.paginator .page-this</span> <span class="token punctuation">{</span><span class="token property">border</span><span class="token punctuation">:</span>1px solid #D3D3D3<span class="token punctuation">;</span><span class="token property">background-color</span><span class="token punctuation">:</span>#E9E9E9<span class="token punctuation">;</span> <span class="token property">color</span><span class="token punctuation">:</span>#D4105A<span class="token punctuation">;</span><span class="token property">padding</span><span class="token punctuation">:</span>0px 8px<span class="token punctuation">;</span> <span class="token property">font-weight</span><span class="token punctuation">:</span>bold<span class="token punctuation">;</span> <span class="token punctuation">}</span>
<span class="token selector">.paginator .page-skip</span> <span class="token punctuation">{</span><span class="token property">height</span><span class="token punctuation">:</span>22px<span class="token punctuation">;</span> <span class="token property">line-height</span><span class="token punctuation">:</span>22px<span class="token punctuation">;</span> <span class="token property">padding</span><span class="token punctuation">:</span>0 3px<span class="token punctuation">;</span> <span class="token property">margin</span><span class="token punctuation">:</span>0<span class="token punctuation">;</span> <span class="token property">background</span><span class="token punctuation">:</span>none<span class="token punctuation">;</span> <span class="token punctuation">}</span>
<span class="token selector">.paginator .page-skip input</span> <span class="token punctuation">{</span><span class="token property">width</span><span class="token punctuation">:</span>26px<span class="token punctuation">;</span>  *<span class="token property">width</span><span class="token punctuation">:</span>23px<span class="token punctuation">;</span><span class="token property">height</span><span class="token punctuation">:</span>19px<span class="token punctuation">;</span><span class="token property">line-height</span><span class="token punctuation">:</span>19px<span class="token punctuation">;</span><span class="token property">border</span><span class="token punctuation">:</span>1px #D3D3D3 solid<span class="token punctuation">;</span><span class="token property">font-size</span><span class="token punctuation">:</span>12px<span class="token punctuation">;</span> <span class="token property">margin</span><span class="token punctuation">:</span>-1px 6px 0px 6px<span class="token punctuation">;</span>#<span class="token property">margin-top</span><span class="token punctuation">:</span>1px<span class="token punctuation">;</span><span class="token property">_margin-top</span><span class="token punctuation">:</span>0px<span class="token punctuation">;</span><span class="token property">padding</span><span class="token punctuation">:</span>0px 0px 0px 2px<span class="token punctuation">;</span> <span class="token property">vertical-align</span><span class="token punctuation">:</span>middle<span class="token punctuation">;</span> <span class="token property">padding-top</span><span class="token punctuation">:</span>0px<span class="token punctuation">;</span> <span class="token property">padding-bottom</span><span class="token punctuation">:</span>0px<span class="token punctuation">;</span> <span class="token punctuation">}</span>
<span class="token selector">.paginator .page-skip button</span> <span class="token punctuation">{</span><span class="token property">font-size</span><span class="token punctuation">:</span>12px<span class="token punctuation">;</span> <span class="token property">padding</span><span class="token punctuation">:</span>0 5px 5px 5px<span class="token punctuation">;</span><span class="token property">_padding</span><span class="token punctuation">:</span>0 5px 0 5px<span class="token punctuation">;</span> <span class="token property">width</span><span class="token punctuation">:</span>auto<span class="token punctuation">;</span> <span class="token property">_width</span><span class="token punctuation">:</span>0<span class="token punctuation">;</span> <span class="token property">height</span><span class="token punctuation">:</span>22px<span class="token punctuation">;</span>  *<span class="token property">height</span><span class="token punctuation">:</span>23px<span class="token punctuation">;</span> *<span class="token property">line-height</span><span class="token punctuation">:</span>20px<span class="token punctuation">;</span> <span class="token property">_height</span><span class="token punctuation">:</span>16px<span class="token punctuation">;</span> <span class="token property">_line-height</span><span class="token punctuation">:</span>16px<span class="token punctuation">;</span> <span class="token property">margin-left</span><span class="token punctuation">:</span>10px<span class="token punctuation">;</span>  *<span class="token property">margin-top</span><span class="token punctuation">:</span>-1px<span class="token punctuation">;</span><span class="token property">overflow</span><span class="token punctuation">:</span>visible<span class="token punctuation">;</span> <span class="token property">vertical-align</span><span class="token punctuation">:</span>top<span class="token punctuation">;</span> <span class="token punctuation">}</span>
<span class="token selector">.paginator a:hover</span> <span class="token punctuation">{</span><span class="token property">border</span><span class="token punctuation">:</span>1px solid #A6A6A6<span class="token punctuation">;</span><span class="token property">color</span><span class="token punctuation">:</span>#868688<span class="token punctuation">;</span> <span class="token punctuation">}</span>
</span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>style</span><span class="token punctuation">></span></span>

<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>pageItems</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>page_wrap<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>paginator<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>pageItem</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>PreviousPage<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>yes</span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>page-prev<span class="token punctuation">"</span></span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>{Current.Url}<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>上一页<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>yes</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>no</span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>span</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>page-start<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>上一页<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>span</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>no</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>pageItem</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>pageItem</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>PageNavigation<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>yes</span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>{Current.Url}<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>{Current.Num}<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>yes</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>no</span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>span</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>page-this<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>{Current.Num}<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>span</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>no</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>pageItem</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>pageItem</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>NextPage<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>yes</span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>page-next<span class="token punctuation">"</span></span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>{Current.Url}<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>下一页<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>yes</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>no</span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>span</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>page-end<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>下一页<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>span</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>no</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>pageItem</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>pageItems</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br><span class="line-number">42</span><br><span class="line-number">43</span><br><span class="line-number">44</span><br><span class="line-number">45</span><br><span class="line-number">46</span><br><span class="line-number">47</span><br><span class="line-number">48</span><br><span class="line-number">49</span><br><span class="line-number">50</span><br><span class="line-number">51</span><br><span class="line-number">52</span><br><span class="line-number">53</span><br><span class="line-number">54</span><br><span class="line-number">55</span><br><span class="line-number">56</span><br><span class="line-number">57</span><br><span class="line-number">58</span><br><span class="line-number">59</span><br></div></div></template>