<template><h1 id="stl-querystring-sql-查询语句"><a class="header-anchor" href="#stl-querystring-sql-查询语句">#</a> <a href="stl:queryString">stl:queryString</a> SQL 查询语句</h1>
<div class="language-markup ext-html line-numbers-mode"><pre v-pre class="language-markup"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>queryString</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>queryString</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h3 id="说明"><a class="header-anchor" href="#说明">#</a> 说明</h3>
<p>通过 <code>stl:queryString</code> 标签在模板中定义 SQL 查询语句</p>
<p><code>&lt;stl:queryString&gt;</code> 必须作为 <code>&lt;stl:sqlContents&gt;</code> 或者 <code>&lt;stl:pageSqlContents&gt;</code> 的子标签使用。 <code>&lt;stl:queryString&gt;</code> 用于设置数据库查询语句（SQL 语句），在此标签内放置 SQL 语句。</p>
<p><code>&lt;stl:queryString&gt;</code> 中定义的 SQL 语句内可以嵌入 STL 语句，如<code>{Channel.ChannelId}</code>当前栏目 Id、<code>{Stl.SiteId}</code>站点 Id 等。</p>
<p>如果为动态调取（在<code>&lt;stl:dynamic&gt;</code>内部使用），可以采用<code>{Request}</code>实体获取页面地址栏参数，如当前页面地址为“page.html#123”，即可使用<code>{Request.Id}</code>获取值并放到 SQL 语句中作为查询条件。</p>
<p><code>&lt;stl:queryString&gt;</code> 标签对应的实体为<code>{stl:queryString}</code>。</p>
<h3 id="示例"><a class="header-anchor" href="#示例">#</a> 示例</h3>
<p><strong>显示最新添加的内容列表</strong></p>
<p>下面的例子显示按最新添加时间获取内容列表。</p>
<div class="language-markup ext-html line-numbers-mode"><pre v-pre class="language-markup"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>sqlContents</span> <span class="token attr-name">connectionStringName</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>ConnectionString<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>queryString</span><span class="token punctuation">></span></span>
    SELECT TOP 10 * FROM model_Content WHERE SiteId = {stl.SiteId} AND ChannelId > 0 ORDER BY AddDate DESC
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>queryString</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>sqlContent</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>Title<span class="token punctuation">"</span></span> <span class="token attr-name">wordnum</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>20<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>sqlContent</span><span class="token punctuation">></span></span>
  (<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token namespace">stl:</span>sqlContent</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>AddDate<span class="token punctuation">"</span></span> <span class="token attr-name">formatString</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>yyyy-MM-dd<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>sqlContent</span><span class="token punctuation">></span></span>)
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>br</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token namespace">stl:</span>sqlContents</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br></div></div></template>